### PR TITLE
Remove check for docblock when trying to find parent entities (#54)

### LINKED ISSUE #54: Child entities are not added to registry when using attributes🐛
### No duplicates 🥲.

- [ ] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Problem:
When using inheritance and mark parent and child classes as entities using attributes, `\Cycle\Schema\Registry` generator does not add children entities to Schema Registry.

How to reproduce:
You can reproduce it if you remove docblock comment for your annotation in tests. You can see an example here
https://github.com/makedo/annotated/tree/fail-test
I change 1 fixture by fully removing docblocks and keep only AttributeReader in tests

Proposed solution:
Remove check for docblock In `Cycle\Annotated\Utils\EntityUtils::findParent`

### Version

annotated v3.1.0,  orm v2.1.1,  PHP 8.1

### ORM Schema

_No response_

### PR DESCRIPTION
**Pull request by makedo**

### CODE REVIEW

**Comment by roxblnfk** [comment]
Can you add test case?

**Comment by makedo** [comment]
> Can you add test case?

Added test case. Not sure if the way test implemented is fine. Thank you.

**Review by butschster — APPROVED** [review]

**Comment by roquie** [comment]
After this fix I got generated extra columns from child entities in parent class (JTI usage) schema declaration. Don't merge it. Need complex test and code refactoring.

**Comment by roxblnfk** [comment]
@msmakouz may be related to https://github.com/cycle/annotated/pull/65

**Comment by msmakouz** [comment]
> After this fix I got generated extra columns from child entities in parent class (JTI usage) schema declaration. Don't merge it. Need complex test and code refactoring.

Hi, this bug fixed by: #65

**Review by msmakouz — APPROVED** [review]

**Review by roxblnfk — APPROVED** [review]

**Pull request merged**
